### ISSUE TITLE
`height.increment()` not needed for Beefy

### ISSUE THREAD

**Issue by livelybug** [informalsystems/hermes#1845]
Hello,

When implementing Beefy protocol, based on Grandpa consensus, there are 3 kinds of verifications in a hierarchical structure.
* The top tier verification is MMR root verification, by collecting sufficient validators' valid signatures. 
* Based on a valid MMR root, the 2nd tier is [block header verification](https://github.com/informalsystems/ibc-rs/issues/1775#issuecomment-1016043500).
* Based on a valid block header,  the 3rd tier is [on-chain storage verification](https://github.com/octopus-network/substrate/blob/33c518ebbe43d38228ac47e793e4d1c76738a56d/primitives/state-machine/src/lib.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1078), which calculates the correct on-chain storage by the state root, the storage proof, and the storage key. A successful verification needs the state root and storage proof to be from the same block. However, as the `height` is increased by one when composing proofs of [connection](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L407),  [channel](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L425), and [packet](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L457), the corresponding state root always belong to the header of block height `N + 1`, while the storage proof belongs to block height `N`, resulting in a failed verification

Understand the `height.increment()` may be for Tendermint consensus, is it possible to compose a trait for it, and allow consensus-specific implementation?

Thank you

**Comment by lyqingye** [comment]
I guess it's because the consensusstate contains the app hash (merkleroot) of the previous block, so PacketProof Height  = ConsensusState Height + 1

**Comment by adizere** [comment]
Hey @livelybug and @lyqingye, many thanks for documenting this!

We can add consensus-specific implementations for the relayer's logic when it is composing proofs of [connection](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L407),  [channel](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L425), and [packet](https://github.com/informalsystems/ibc-rs/blob/e16d5f64fdf7bbd6e0fa9449a567ad9ee1b3c180/relayer/src/chain.rs#L457).

## Refining the problem

These three methods of trait `ChainEndpoint` have too many responsibilities:
1. build_connection_proofs_and_client_state
2. build_channel_proofs
3. build_packet_proofs

They each have two responsibilities: (A) preparing the different [sub-elements](https://github.com/informalsystems/ibc-rs/blob/9edf729331fcce73473f9277373ddab8df00189c/modules/src/proofs.rs#L22-L26) of a `Proof` -- such as object, client, or consensus proofs -- from (B) assembling a coherent `Proof` from these sub-elements (including the correct height within the proof) by calling into `Proof::new`.

Part (A) is generic for all IBC-enabled chains as far as I can tell. Part (B) is chain (i.e., consensus-protocol) specific. So the fix would be to decouple (A) from (B).

## Acceptance criteria

- [ ] The three methods of `ChainEndpoint` mentioned above should only implement part (A), they should call in to `Proofs::new` and handle `height.increment()` (this is (B)) since that is not their responsibility.
- [ ] For the final construction of a Proof (point (B)), these methods should delegate to a __new__ method `assemble_proof` defined on the `ChainEndpoint` trait.
    - The `CosmosSdk` implementation of `ChainEndpoint: assemble_proof` method will simply call into `Proof::new` while incrementing the height.
    - Other chain implementations will assemble proofs without increasing the height.

@livelybug let me know if you agree with the scope & acceptance criteria.

**Comment by livelybug** [comment]
> 

Thank you, Adi! I am fine with the scope & acceptance criteria.
