### ISSUE TITLE
Add support for using PeriodicVestingAccount for the relayer account

### ISSUE THREAD

**Issue by PFC-developer** [informalsystems/hermes#2744]
## Summary of Bug

unable to create a channel due to unknown protobuf account

## Version

`hermes 1.0.0+ed4dd8c8
`
## Steps to Reproduce

` hermes create channel --a-chain phoenix-1 --b-chain columbus-5 --a-port transfer --b-port transfer --new-client-connection
`

and it returns

`ERROR error raised while creating client for chain phoenix-1: failed sending message to dst chain : Failed to deserialize account of an unknown protobuf type: /cosmos.vesting.v1beta1.PeriodicVestingAccount
`
## Acceptance Criteria

it can create the channel
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Thank you for opening an issue!

Continuing the discussion from Discord here.

> my initial thought was this was due to columbus-5 being a old chain, and maybe I need to use a older version of hermes?

I doubt it's due to `columbus-5`. It's unlikely related or specific to a version of Hermes.

Like I mentioned earlier, I think we don't support at the moment `PeriodicVestingAccount`, only `cosmos.auth.v1beta1.BaseAccount` or `*.EthAccount`. This error is related to the wallet you've configured in Hermes for using with chain `phoenix-1`. The config param is `key_name` (ref https://github.com/informalsystems/hermes/blob/41aec7154e4fee51fba803d021c4541ef8902228/config.toml#L128). Specifically, this wallet cannot be a `PeriodicVestingAccount`.

We might be able to support this.

### Action items for you

1. Can you help us by providing the output for this command:

```bash
  hermes keys balance --chain phoenix-1
```

2. I don't see public RPCs available for phoenix-1 in the chain registry. Do you know any RPC node for that network we can use?

**Comment by PFC-developer** [comment]
1.
```
$ hermes keys balance --chain phoenix-1
2022-10-19T13:28:11.031623Z  INFO ThreadId(01) using default configuration from '/home/hermes/.hermes/config.toml'
SUCCESS balance for key `terrakey`: 1505247 uluna
$
```
2. RPC keys
```
https://terra2-rpc.dalnim.finance/ -- phoenix-1
https://terra-rpc.dalnim.finance/ -- columbus-5
```

**Comment by PFC-developer** [comment]
```
$ hermes keys list --chain phoenix-1
2022-11-01T14:47:50.000557Z  INFO ThreadId(01) using default configuration from '/home/hermes/.hermes/config.toml'
SUCCESS
- terrakey (terra14cpqjy6tfryrqlwyycyy7hca5uzrdyqh0leked)
```

as for why? I didn't specifically create it that way. It could be a hold-over from pre-depeg luna (in may) and it was just migrated over this way.

**Comment by adizere** [comment]
I found this info:

- https://docs.cosmos.network/v0.45/modules/auth/05_vesting.html#intro-and-requirements
- The account you're using is this one https://cosmosrun.info/terra-phoenix-1/account/terra14cpqjy6tfryrqlwyycyy7hca5uzrdyqh0leked
    - Not all accounts on phoenix-1 are of type `cosmos-sdk/PeriodicVestingAccount`, for instance this one is `cosmos-sdk/BaseAccount` https://cosmosrun.info/terra-phoenix-1/account/terra1l4v02k8azrekgzjahjdgaaplr4tlnmlc4eelrx

**Comment by PFC-developer** [comment]
aah..ok.. so it's due to it being a migrated account.
I'll adjust and retry.
do you want to close this, or are you planning on adding the protobuf entry?
(ie. feel free to close, as my issue is mitigated)

**Comment by adizere** [comment]
> aah..ok.. so it's due to it being a migrated account.
> I'll adjust and retry.
> do you want to close this, or are you planning on adding the protobuf entry?
> (ie. feel free to close, as my issue is mitigated)

I see. Thanks for the quick update! Since your issue is mitigated, I'll close it.

If you feel like you'd like support for this in the future, please let us know.

_Technical details:_ Adding support for `PeriodicVestingAccount` would need Hermes to import the SDK's [vesting](https://github.com/cosmos/cosmos-sdk/tree/v0.46.3/proto/cosmos/vesting/v1beta1) proto files, which means patching `ibc-proto-rs` to [include those files](https://github.com/cosmos/ibc-proto-rs/blob/2cf514366768ddef257db3283a0b8bcb4bf9638a/tools/proto-compiler/src/cmd/compile.rs#L47). So this feature requires an upgrade to crate `ibc-proto-rs` in addition to upgrade to Hermes. This is not  difficult, but needs a bit of wrangling, so we will do it if the need for it arises.
