### ISSUE TITLE
release workflow for arm64 linux failed in github actions

### ISSUE THREAD

**Issue by allthatjazzleo** [informalsystems/hermes#2885]
## Summary

release workflow failed in ubuntu-latest, aarch64-unknown-linux-gnu

## Problem Definition

```
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"
```

## Acceptance Criteria

can release arm64 binary for linux
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
Thanks for the PR! But I think this has since been fixed by removing the dependency on OpenSSL altogether on master.

Can you get into more details as to why this would be required now that OpenSSL is no longer a dependency?

For more context, see https://github.com/informalsystems/hermes/pull/2856#issuecomment-1311408868

**Comment by romac** [comment]
Or perhaps this is a different problem?
