### ISSUE TITLE
Move Docker images from Docker Hub over to GitHub

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3187]
## Proposal

Docker is [restricting their free plan](https://blog.alexellis.io/docker-is-deleting-open-source-images/) for open-source organizations and we should plan for that.

I suggest we copy our existing Docker images from Docker Hub over to the GitHub Container Repository and start publishing the new ones to both Docker Hub and GHCR.

As a test, I have already published the v1.3.0 image on GitHub, which can be [accessed here](https://github.com/informalsystems/hermes/pkgs/container/hermes).

## Acceptance Criteria

- [ ] All existing Docker images are published on GCHR
- [ ] The release job on CI is updated to publish images to both Docker Hub and GHCR

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
@romac Is there anything else that still needs to be done as part of this issue? I see that we've published all versions of Hermes since v1.3 to GHCR. 

I suppose we could publish older versions of Hermes to GHCR as well, but at this point, I'm more inclined to just continue publishing new releases of Hermes to GHCR and consider this issue completed, unless there's something I'm missing.

**Comment by romac** [comment]
Right, let's close this!
