### ISSUE TITLE
Introduce `(PortId, ChannelId)` domain type

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#745]
## Crate

`ibc`

## Summary

Since we started working on ICS04 handlers(https://github.com/informalsystems/ibc-rs/pull/452) we noticed that there is a recurring need to encapsulate the tuple `(PortId, ChannelId)` as a type. This tuple is needed in error types:

https://github.com/informalsystems/ibc-rs/blob/d6250014e8d8fcddde651f9e3ceb6be5c93cbeae/modules/src/application/ics20_fungible_token_transfer/error.rs#L19-L20

or as parameters to structures:

https://github.com/informalsystems/ibc-rs/blob/71d9baa6a2eed5a9286f9fe88f1cfacbd51e19d8/modules/src/mock/context.rs#L86-L86

or as parameters to methods:

https://github.com/informalsystems/ibc-rs/blob/71d9baa6a2eed5a9286f9fe88f1cfacbd51e19d8/modules/src/mock/context.rs#L279-L282

So there's ample reasons to introduce a new type for capturing the two.

## Proposal

The new type should probably reside in ICS04. Potential names:

```rust
pub struct PortChannel(PortId, ChannelId);
pub struct BoundChannel(PortId, ChannelId);
pub struct AuthorizedChannel(PortId, ChannelId);
```

____

#### For Admin Use

- [X] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
How about `IbcSocket`? Much like a TCP socket consists of an IP address and a port number.

**Comment by adizere** [comment]
Blocked on https://github.com/cosmos/ibc/issues/583

**Comment by mzabaluev** [comment]
We can invent the type locally (already have as `PortChannelId`?) and use it in any internal or domain/idiomatic wrapper interfaces without the need for protobuf to be modified. In fact, a message type just to group the two fields consumes more space in protobuf wire encoding than the same two fields encoded inline.

> Potential names:

`Socket`?

> `BoundChannel(PortId, ChannelId)`

This looks too "stateful": there may not be a bound channel for this pair of IDs, as there isn't in your example of an error where this type could be used.

**Comment by romac** [comment]
I kinda like _socket_ but i am afraid it's already too overloaded.

I agree that `BoundChannel` is too stateful.

**Comment by plafer** [comment]
I don't like `Socket` because IMO, in TCP/IP an `(address, port)` is more an "endpoint" than a "socket". For me, a socket represents a data structure over which I can *perform operations*; it is an interface provided by the kernel that lets me read/write the network. A socket is definitely stateful to me: it holds everything needed to properly interact with the network (e.g. the sequence number in the case of IBC). In other words, `ChannelEnd` is more a "socket" to me than `(address, port)` is.

I can't think of another analogy that I feel fits IBC's `(channelId, portId)`, so I think I would vote for the simple `PortChannelId`.

**Comment by romac** [comment]
Good points! Let's go with `PortChannelId` then of nobody has a better suggestion.
