### ISSUE TITLE
Modular logic for ICS3 Connection handshake protocol

### ISSUE THREAD

**Issue by milosevic** [informalsystems/hermes#92]
Before relayer forward IBC message to the destination, it is supposed to do checks (commitment proofs checks, business logic checks) equivalent to the checks done on chain by the corresponding ICS message handler. 

The idea is to implement these checks, directly in the `ibc` crate, in a modular manner so that both the IBC modul and the relayer create can use them. As part of this larger task we need to implement the various verification method similar as defined in `ClientState`: https://github.com/cosmos/cosmos-sdk/blob/55796fb3e73c222eb97c1308d4eee26144e8189f/x/ibc/02-client/exported/exported.go#L17.

**Comment by adizere** [comment]
Given the addition of domain types (which handle message validation), it's unclear if this issue is still relevant. There is some potential to reuse business logic of processing certain messages, however. So we can investigate this in the context of ICS3 specifically, while implementing #377. The goal would be that relayer-side logic would import and reuse verification functions (not only for clients & proofs).

**Comment by adizere** [comment]
Cf: https://github.com/informalsystems/ibc-rs/pull/388#discussion_r520455471

**Comment by adizere** [comment]
Closing as stale.
